sudo: required
services:
    - docker

before_install:
    - docker build -t amitecs07/docker-tut -f Dockerfile.dev .

script:
    - docker run -e CI=true amitecs07/docker-tut npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-083052042026"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
